### ISSUE TITLE
Prefix variables with underscore at broadcast.js

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/conference-broadcast-rails#4]
@jarodreyes is there any reason to prefix some variables with an underscore [here](https://github.com/TwilioDevEd/conference-broadcast-rails/blob/a7c8096c73510cc4fb20f2d38f0f0a8dba06042f/app/assets/javascripts/broadcast.js#L33-L47)?

A more closely look:
```javascript
  populateSelect = function(recordings) {
    var recording, select, _i, _len, _results;
    select = $('#selectRecordings');
    select.empty();
    _results = [];
    // ...
```

I don't feel like this is a standard practice doing JavaScript. I'd like to hear your thoughts about this.

**Comment by jarodreyes** [comment]
Good call.
